<?php

$sqlsreach = array();
$sqlsreach['TEST'] = "SELECT * FROM TEST WHERE RECNO = :RECNO AND DATA = :DATA  AND X = :X NUMBER = :NUMBER ";

$sqlsreach['TEST2'] = "INSERT INTO appointment (CUSTNAME,CONTNAME,TEL) VALUES (:name)";

//QOUT
$sqlsreach['COUNT_QUOTHD0'] = "SELECT QUOTHD.CUST, CUST.NAME AS CustomerName, CUST.CODE  AS CODE, CUST.CORP  AS CORPNAME, COUNT(QUOTHD.CUST) AS QUAN FROM QUOTHD LEFT JOIN CUST ON QUOTHD.CUST = CUST.RECNO GROUP BY QUOTHD.CUST, CUST.NAME, CUST.CODE, CUST.CORP ORDER BY QUAN DESC";

//QOUTINVOICE
$sqlsreach['QOUT_INVOICE_0'] = "SELECT
    INVCHD.RECNO,
    INVCHD.DOCDATE,
    INVCHD.DUEDATE,
    INVCHD.DOCNO,
    INVCHD.SALES,
    INVCHD.ORDERNO,
    INVCDT.DETAIL,
    INVCDT.QUAN,
    INVCDT.UNITAMT,
    INVCDT.TOTALAMT,
    INVCHD.CURCODE,
	  INVCHD.EXCHGRATE,
    CUST.CODE,
    CUST.NAME,
    EMPL.EMPNO,
    EMPL.EMPNAME
    FROM INVCHD
LEFT JOIN CUST ON (INVCHD.CUST = CUST.RECNO)
LEFT JOIN EMPL ON (INVCHD.SALES = EMPL.RECNO)
LEFT JOIN INVCDT ON (INVCHD.RECNO = INVCDT.INVCHD)
WHERE (INVCHD.DOCDATE BETWEEN :ABEGIN AND :AEND) AND (INVCHD.STATUS <> 'C')
ORDER BY INVCHD.RECNO";

$sqlsreach['QOUT_INVOICE_ALL'] = "SELECT
    INVCHD.RECNO,
    INVCHD.DOCDATE,
    INVCHD.DUEDATE,
    INVCHD.DOCNO,
    INVCHD.SALES,
    INVCHD.ORDERNO,
    INVCDT.DETAIL,
    INVCDT.QUAN,
    INVCDT.UNITAMT,
    INVCDT.TOTALAMT,
    INVCHD.CURCODE,
	  INVCHD.EXCHGRATE,
    CUST.CODE,
    CUST.NAME,
    EMPL.EMPNO,
    EMPL.EMPNAME
    FROM INVCHD
LEFT JOIN CUST ON (INVCHD.CUST = CUST.RECNO)
LEFT JOIN EMPL ON (INVCHD.SALES = EMPL.RECNO)
LEFT JOIN INVCDT ON (INVCHD.RECNO = INVCDT.INVCHD)
WHERE(INVCHD.STATUS <> 'C')
ORDER BY INVCHD.RECNO";


//PURCHD
$sqlsreach['COUNT_PURCHD0'] = "SELECT PURCHD.SUPP, SUPP.NAME AS SUPPOMERNAME, SUPP.CODE  AS CODE, SUPP.CORP  AS CORPNAME, COUNT(PURCHD.SUPP) AS QUAN FROM PURCHD LEFT JOIN SUPP ON PURCHD.SUPP = SUPP.RECNO GROUP BY PURCHD.SUPP, SUPP.NAME, SUPP.CODE, SUPP.CORP ORDER BY QUAN DESC";


//CUSTOMER 
$sqlsreach['CUST_LIST'] =  "SELECT RECNO,NAME,CODE  FROM cust ORDER BY CODE ASC";
$sqlsreach['CUSTCONT_LIST'] =  "SELECT RECNO,CONTNAME,CONTTEL,CONTEMAIL FROM custcont WHERE CUST=:CUST AND CONTNAME <> '' ";


//INVENT


// TOTAL
$sqlsreach['selectyear'] = "SELECT EXTRACT(YEAR FROM DOCDATE) AS AYEAR FROM INVCHD WHERE (STATUS <> 'C') AND (EXTRACT(YEAR FROM DOCDATE) BETWEEN :ABEGIN AND :END) GROUP BY AYEAR ORDER BY AYEAR ROWS 3";


// ACTIVITY
$sqlsreach['IND_ACTIVITYHD'] = "INSERT INTO activityhd (CREATED,LASTUPD,STATUS,DOCNO,CUST,CONT,CUSTNAME,CONTNAME,TEL,EMAIL,ADDR,LOCATION,SUBJECT,DETAIL,REF,PRIORITY,TIMED,TIMEH,TIMEM,STARTD,WARND,PRICECOST,PRICEPWITHDRAW,OWNER,OWNERNAME,REMARK) VALUES (NOW(), NOW(),:STATUS,:DOCNO,:CUST,:CONT,:CUSTNAME,:CONTNAME,:TEL,:EMAIL,:ADDR,:LOCATION,:SUBJECT,:DETAIL,:REF,:PRIORITY,:TIMED,:TIMEH,:TIMEM,:STARTD,:WARND,:PRICECOST,:PRICEPWITHDRAW,:OWNERNUM,:OWNERNAMESTR,:REMARK)";
$sqlsreach['SEL_ACTIVITYHD'] = "SELECT * FROM activityhd";
$sqlsreach['EDSEL_ACTIVITYHD'] = "SELECT * FROM activityhd WHERE RECNO = :RECNO";
$sqlsreach['DATESEL_ACTIVITYHD'] = "SELECT * FROM activityhd WHERE  STARTD = :STARTD ";
// $sqlsreach['DATESEL_ACTIVITYHD'] ="SELECT * FROM ACTIVITYHD WHERE STARTD = :STARTD ";
$sqlsreach['UPD_ACTIVITYHD'] = "UPDATE activityhd SET LASTUPD = 'NOW', STATUS = :STATUS, CUST = :CUST, CONT = :CONT, CUSTNAME = :CUSTNAME, CONTNAME = :CONTNAME, TEL = :TEL, EMAIL = :EMAIL, ADDR = :ADDR, LOCATION = :LOCATION, SUBJECT = :SUBJECT, DETAIL = :DETAIL, REF = :REF, PRIORITY = :PRIORITY, TIMED = :TIMED, TIMEH = :TIMEH, TIMEM = :TIMEM, STARTD = :STARTD,WARND = :WARND, PRICECOST = :PRICECOST, PRICEPWITHDRAW = :PRICEPWITHDRAW, OWNER = :OWNERNUM, OWNERNAME = :OWNERNAMESTR,REMARK = :REMARK  WHERE RECNO = :RECNO";
$sqlsreach['DLT_ACTIVITYHD'] =  "DELETE FROM activityhd WHERE RECNO = :RECNO";


//EQUIPMENT
$sqlsreach['EQUIPMENT'] = "INSERT INTO equipment (CREATED,DOCNO, NAME, CODE, TYPE, MODEL, CUSTNAME, CONTNAME, PHONE, EMAIL, STATUS, DOCINFO, PRIORITY, MAINTENANCETIMES, BROKENTIMES, WARRANTY, PURCHASEDATE, FIRSTUSAGE, LASTUSAGE, DETAILS, RECORDERNO, RECORDERNAME, AREA, UPLOAD) VALUES (NOW(),:DOCNO, :NAME, :CODE, :TYPE, :MODEL, :CUSTNAME, :CONTNAME, :PHONE, :EMAIL, :STATUS, :DOCINFO, :PRIORITY, :MAINTENANCETIMES, :BROKENTIMES, :WARRANTY, :PURCHASEDATE, :FIRSTUSAGE, :LASTUSAGE, :DETAILS, :RECORDERNO, :RECORDERNAME, :AREA, :UPLOAD)";
$sqlsreach['SEL_EQUIPMENT'] = "SELECT * FROM equipment";
$sqlsreach['EDSEL_EQUIPMENT'] = "SELECT * FROM equipment WHERE RECNO = :RECNO";
$sqlsreach['UPD_EQUIPMENT'] =  "UPDATE equipment SET NAME = :NAME, CODE = :CODE, TYPE = :TYPE, MODEL = :MODEL, CUSTNAME = :CUSTNAME, CONTNAME = :CONTNAME, PHONE = :PHONE, EMAIL = :EMAIL, STATUS = :STATUS, DOCINFO = :DOCINFO, PRIORITY = :PRIORITY, MAINTENANCETIMES = :MAINTENANCETIMES, BROKENTIMES = :BROKENTIMES, WARRANTY = :WARRANTY, PURCHASEDATE = :PURCHASEDATE, FIRSTUSAGE = :FIRSTUSAGE, LASTUSAGE = :LASTUSAGE, DETAILS = :DETAILS, RECORDERNO = :RECORDERNO, RECORDERNAME = :RECORDERNAME, AREA = :AREA, UPLOAD = :UPLOAD WHERE RECNO = :RECNO";
$sqlsreach['EQUIPMENT_LIST'] =  "SELECT RECNO,NAME,CODE  FROM equipment ORDER BY RECNO ASC";

//NOTIMAINTEN
$sqlsreach['SEL_NOTIMAINTEN'] = "SELECT nm.RECNO,nm.DOCNO, nm.NAME, nm.CONTNAME, nm.STATUS, nm.PRIORITY, nm.PRICECOST, nm.PRICEPWITHDRAW, nm.WARNINGDATE, nm.DETAILS, nm.RECORDERNO, nm.RECORDERNAME, eq.NAME AS EQUIPMENT_NAME FROM notimainten nm left JOIN equipment eq ON nm.EQUIPMENT = eq.RECNO";
$sqlsreach['IND_NOTIMAINTEN'] = "INSERT INTO notimainten (CREATED, DOCNO, NAME, CONTNAME, EQUIPMENT, STATUS, PRIORITY, PRICECOST, PRICEPWITHDRAW, WARNINGDATE, DETAILS, RECORDERNO, RECORDERNAME) VALUES (NOW(), :DOCNO, :NAME, :CONTNAME, :EQUIPMENT, :STATUS, :PRIORITY, :PRICECOST, :PRICEPWITHDRAW, :WARNINGDATE, :DETAILS, :RECORDERNO, :RECORDERNAME)";
$sqlsreach['UPD_NOTIMAINTEN'] = "UPDATE notimainten SET NAME = :NAME, CONTNAME = :CONTNAME, EQUIPMENT = :EQUIPMENT, STATUS = :STATUS, PRIORITY = :PRIORITY, PRICECOST = :PRICECOST, PRICEPWITHDRAW = :PRICEPWITHDRAW, WARNINGDATE = :WARNINGDATE, DETAILS = :DETAILS, RECORDERNO = :RECORDERNO, RECORDERNAME = :RECORDERNAME WHERE RECNO = :RECNO;";
$sqlsreach['EDSEL_NOTIMAINTEN'] = "SELECT * FROM notimainten WHERE RECNO = :RECNO";

//EMPLOYEE
$sqlsreach['EMPL_LIST'] =  "SELECT RECNO,EMPNAME,EMPNO  FROM empl ORDER BY EMPNO ASC";
$sqlsreach['ALL_EMPL_LIST'] =  "SELECT * FROM empl";
$sqlsreach['EDSEL_EMP'] = "SELECT * FROM empl WHERE RECNO = :RECNO";
$sqlsreach['IND_EMPL'] =  "INSERT INTO empl (LASTUPD, PERMISSION, STATUS, USERLEVEL, EMPNO, EMPNAME, EMPNAMEEN, EMPNICK, LOGIN, PASS, CREATED, IMG) VALUES (NOW() ,'' ,'T' ,:USERLEVEL ,:EMPNO ,:EMPNAME ,'' ,:EMPNICK ,:LOGIN ,:PASS ,NOW() ,:IMG)";
$sqlsreach['UPD_EMPL'] =  "UPDATE empl SET LASTUPD = NOW(), STATUS = 'T', USERLEVEL = :USERLEVEL, EMPNO = :EMPNO, EMPNAME = :EMPNAME, EMPNICK = :EMPNICK, LOGIN = :LOGIN, PASS = :PASS, CREATED = NOW(), IMG = :IMG WHERE RECNO = :RECNO";
$sqlsreach['DLT_EMPL'] =  "DELETE FROM empl WHERE RECNO = :RECNO";

//DRAWING
$sqlsreach['SEL_DRAWING'] = "SELECT * FROM drawing";
$sqlsreach['EDSEL_DRAWING'] = "SELECT * FROM drawing WHERE RECNO = :RECNO";
$sqlsreach['IND_DRAWING'] = "INSERT INTO drawing (CREATED, LASTUPD,STATUS, CUSTOMER, DRAWNO, REVNO, PARTNAME, RECDATE, REMARK, CREATEDBY, MODIFIEDBY) VALUES (NOW(), NOW(),'A',:CUSTOMER, :DRAWNO, :REVNO, :PARTNAME, :RECDATE, :REMARK, :MODIFIEDBY, :MODIFIEDBY)";
$sqlsreach['CHECK_DRAWING'] = "SELECT COUNT(*) FROM drawing WHERE  DRAWNO = :DRAWNO";
$sqlsreach['UPD_DRAWING'] = "UPDATE drawing SET CUSTOMER = :CUSTOMER, DRAWNO = :DRAWNO, REVNO = :REVNO, PARTNAME = :PARTNAME, RECDATE = :RECDATE, REMARK = :REMARK, MODIFIEDBY = :MODIFIEDBY, LASTUPD = NOW() WHERE RECNO = :RECNO;";
$sqlsreach['MOUPD_DRAWING'] = "UPDATE drawing SET  STATUS = 'D', LASTUPD = NOW() WHERE RECNO = :RECNO;";


//SALE

$sqlsreach['EXCEL_CUSTOMERSALE'] = "SELECT QUOTHD.RECNO, QUOTHD.DOCDATE, QUOTHD.DOCNO, QUOTHD.REVISE, CUST.CODE, CUST.SNAME, CUST.NAME, CUSTCONT.CONTNAME, QUOTDT.DETAIL, EMPL.EMPNAME, QUOTHD.CREDIT, QUOTHD.REMARK, QUOTDT.QUAN, QUOTDT.UNITAMT, QUOTDT.TOTALAMT FROM QUOTHD LEFT JOIN CUST ON (QUOTHD.CUST = CUST.RECNO) LEFT JOIN CUSTCONT ON (QUOTHD.CONT = CUSTCONT.RECNO) LEFT JOIN EMPL ON (QUOTHD.SALES = EMPL.RECNO) LEFT JOIN quotdt ON (QUOTHD.RECNO = quotdt.QUOTHD) WHERE  (QUOTHD.STATUS <> 'C') AND  (QUOTDT.DETAIL <> '')  AND (QUOTHD.DOCDATE BETWEEN :ABEGIN AND :AEND) ORDER BY QUOTHD.RECNO";


$sqlsreach['EXCEL_QOUT_INVOICE'] = "SELECT
    INVCHD.RECNO,
    INVCHD.DOCDATE,
    INVCHD.DOCNO,
    INVCHD.ORDERNO,
    CUST.CODE, 
    CUST.SNAME, 
    CUST.NAME,
    CUSTCONT.CONTNAME,
    EMPL.EMPNAME,
    INVCDT.DETAIL,
    INVCDT.QUAN,
    INVCDT.UNITAMT,
    INVCDT.TOTALAMT
    FROM INVCHD
LEFT JOIN CUST ON (INVCHD.CUST = CUST.RECNO)
LEFT JOIN CUSTCONT ON (INVCHD.CONT = CUSTCONT.RECNO)
LEFT JOIN EMPL ON (INVCHD.SALES = EMPL.RECNO)
LEFT JOIN INVCDT ON (INVCHD.RECNO = INVCDT.INVCHD)
WHERE (INVCHD.DOCDATE BETWEEN :ABEGIN AND :AEND) AND (INVCDT.DETAIL <> '')  AND (INVCHD.STATUS <> 'C')
ORDER BY INVCHD.RECNO";


$sqlsreach['EXCEL_QOUT_ORDERHD'] = "SELECT
ORDERHD.RECNO,
ORDERHD.DOCDATE,
ORDERHD.DOCNO,
ORDERHD.CUSTORDERNO,
CUST.CODE, 
CUST.SNAME, 
CUST.NAME,
CUSTCONT.CONTNAME,
EMPL.EMPNAME,
ORDERDT.DETAIL,
ORDERDT.QUANDLY,
ORDERDT.UNITAMT,
ORDERDT.TOTALAMT
FROM ORDERHD
LEFT JOIN CUST ON (ORDERHD.CUST = CUST.RECNO)
LEFT JOIN CUSTCONT ON (ORDERHD.CONT = CUSTCONT.RECNO)
LEFT JOIN EMPL ON (ORDERHD.SALES = EMPL.RECNO)
LEFT JOIN ORDERDT ON (ORDERHD.RECNO = ORDERDT. ORDERHD)
WHERE (ORDERHD.DOCDATE BETWEEN :ABEGIN AND :AEND)  AND  (ORDERDT.DETAIL <> '')  AND (ORDERHD.STATUS <> 'C')
ORDER BY ORDERHD.RECNO";



$sqlsreach['EXCEL_QOUT_DELYHD'] = "SELECT
DELYHD.RECNO,
DELYHD.DOCDATE,
DELYHD.DOCNO,
DELYHD.ORDERHD,
CUST.CODE, 
CUST.SNAME, 
CUST.NAME,
EMPL.EMPNAME,
DELYDT.DETAIL,
DELYDT.QUAN,
DELYDT.UNITAMT,
DELYDT.TOTALAMT
FROM DELYHD
LEFT JOIN CUST ON (DELYHD.CUST = CUST.RECNO)
LEFT JOIN EMPL ON (DELYHD.SALES = EMPL.RECNO)
LEFT JOIN DELYDT ON (DELYHD.RECNO = DELYDT.DELYHD)
WHERE (DELYHD.DOCDATE BETWEEN :ABEGIN AND :AEND)  AND  (DELYDT.DETAIL <> '')  AND (DELYHD.STATUS <> 'C')
ORDER BY DELYHD.RECNO";

function sqlexec($queryId)
{
  global $sqlsreach;
  if (array_key_exists($queryId, $sqlsreach)) {
    $sqlQuery = $sqlsreach[$queryId];
    return $sqlQuery;
  } else {
    return null;
  }
}


function sqlmixexe($queryId, $params)
{
  global $sqlsreach;
  // ตรวจสอบว่ามีคำสั่ง SQL ตามหมายเลขที่กำหนดหรือไม่
  if (array_key_exists($queryId, $sqlsreach)) {
    $sqlQuery = $sqlsreach[$queryId];
    // ตรวจสอบว่า params มีค่าหรือไม่
    if (!empty($params)) {
      // เติมค่าพารามิเตอร์ในคำสั่ง SQL
      foreach ($params as $key => $value) {
        if (isset($value) && !is_array($value)) { // ตรวจสอบว่ามีคีย์ใน $params และไม่ใช่ array
          if ($value === null || $value === '') {
            $sqlQuery = str_replace(":$key", '\'\'', $sqlQuery); // แทนที่ด้วย NULL
          } else {
            $value = is_numeric($value) ? strval($value) : "'" . addslashes($value) . "'"; // เพิ่ม addslashes เพื่อป้องกัน SQL Injection
            $sqlQuery = str_replace(":$key", $value, $sqlQuery);
          }
        }
      }
    }
    return $sqlQuery;
  } else {
    return null;
  }
}
